<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="larcc">

    <xacro:property name="M_PI" value="3.1415926535897931"/>

        <!-- Tables properties-->
    <xacro:property name="table_height" value="0.795"/>
    <xacro:property name="table_width" value=".9"/>
    <xacro:property name="table_length" value="1.25"/>
    <xacro:property name="table_tabletop_thickness" value="0.015"/>
    <xacro:property name="table_leg_radius" value="0.02"/>

    <!-- Gantry properties-->
    <xacro:property name="gantry_height" value="2.29"/>
    <xacro:property name="gantry_foot_height" value="0.065"/>
<!--    <xacro:property name="gantry_height" value="2.353"/>-->
    <xacro:property name="gantry_width" value="4"/>
    <xacro:property name="gantry_length" value="2.7975"/>
    <xacro:property name="gantry_thickness" value="0"/>
    <xacro:property name="gantry_leg_radius" value="0.09"/>

   <link name="world"/>

<!--    Load all macros-->

    <xacro:include filename="$(find larcc_cell_description)/urdf/properties.xacro"/>

    <xacro:include filename="$(find ur_description)/urdf/inc/ur10e_macro.xacro"/>
    <xacro:include filename="$(find realsense2_description)/urdf/test_d435i_camera.urdf.xacro" />
    <xacro:include filename="$(find larcc_cell_description)/urdf/astra.urdf.xacro"/>
    <xacro:include filename="$(find gripper)/urdf/robotiq_arg2f_140_model_macro.xacro" />
    <xacro:include filename="$(find larcc_cell_description)/urdf/table.macro.xacro"/>
    <xacro:include filename="$(find larcc_cell_description)/urdf/gantry.macro.xacro"/>
    <xacro:include filename="$(find larcc_cell_description)/urdf/wood_block.macro.xacro"/>

<!--    Place gantry-->

    <xacro:gantry_macro name="gantry" parent="world" width="${gantry_width}"
                        length="${gantry_length}" height="${gantry_height}" foot_height="${gantry_foot_height}"
                        gantry_thickness="${gantry_thickness}" leg_radius="${gantry_leg_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:gantry_macro>


<!--    Place ur10e robot-->
    <xacro:ur10e_robot prefix="" />

    <joint name="world_to_robot_joint" type="fixed">
        <parent link="tabletop_table_base"/>
        <child link="base_link"/>
        <origin xyz="0 0 -0.015" rpy="0 0 0"/>
    </joint>

<!--    <xacro:sensor_astra prefix="camera_behind" parent="world">-->
<!--        <origin xyz="0.8481721310949765 1.224365708088931 2.3511875266550333"-->
<!--                rpy="-0.19718554582052114 0.5342533504487207 -1.8821968275695813"/>-->
<!--    </xacro:sensor_astra>-->

    <xacro:sensor_astra prefix="camera_top" parent="world">
        <origin xyz="0.09511408182797733 0.14905972847160784 2.4330682231422602"
                rpy="-1.9962039976135075 1.491251777066553 -2.0400319820116386"/>
    </xacro:sensor_astra>

    <xacro:sensor_astra prefix="camera_right" parent="world">
        <origin xyz="-0.47389933117248495 0.6050706033175103 1.2510900165155419"
                rpy="0.1688160669718149 0.3885697035429511 -0.6796268633018927"/>
    </xacro:sensor_astra>

    <xacro:wood_block_macro parent="camera_right_rgb_optical_frame">
        <origin xyz="0 0.25 0.7" rpy="${M_PI/2} 0 0"/>
    </xacro:wood_block_macro>

    <joint name="tool0-FT_sensor_base" type="fixed">
        <parent link="tool0"/>
        <child link="FT_sensor_base"/>
        <origin xyz="0 0 0.007" rpy="0 0 ${M_PI/2}"/>
    </joint>


    <link name="FT_sensor_base">
        <visual>
          <geometry>
            <cylinder length="0.014" radius="0.05"/>
          </geometry>
          <material name="metalic_blue">
            <color rgba="0.0118 0.5176 0.6706 1.0"/>
          </material>
        </visual>
        <collision>
          <geometry>
            <cylinder length="0.014" radius="0.05"/>
          </geometry>
        </collision>
    </link>


    <joint name="FT_sensor_base-FT_sensor" type="fixed">
        <parent link="FT_sensor_base"/>
        <child link="FT_sensor"/>
        <origin xyz="0 0 0.0215" rpy="0 0 0"/>
    </joint>

    <link name="FT_sensor">
        <visual>
          <geometry>
            <cylinder length="0.029" radius="0.04"/>
          </geometry>
          <material name="metalic_blue">
            <color rgba="0.0118 0.5176 0.6706 1.0"/>
          </material>
        </visual>
        <collision>
          <geometry>
            <cylinder length="0.029" radius="0.04"/>
          </geometry>
        </collision>
    </link>



<!--    Place gripper-->
    <xacro:robotiq_arg2f_140 prefix=""/>

    <joint name="gripper_joint" type="fixed">
        <parent link="FT_sensor"/>
        <child link="robotiq_arg2f_base_link"/>
        <origin xyz="0 0 0.0215" rpy="0 0 0"/>
    </joint>

    <link name="end_effector"/>

    <joint name="gripper-end_effector" type="fixed">
        <parent link="robotiq_arg2f_base_link"/>
        <child link="end_effector"/>
        <origin xyz="0 0 0.21573113136562894" rpy="0 0 ${-M_PI/2}"/>
    </joint>


<!--    Place base table-->

    <xacro:table_macro name="table_base" parent="world" width="${table_width}"
                       length="${table_length}" height="${table_height}"
                       tabletop_thickness="${table_tabletop_thickness}" leg_radius="${table_leg_radius}">
        <origin xyz="0.1 ${gantry_length/2-table_width/2} 0" rpy="0 0 ${-M_PI/2}"/>
    </xacro:table_macro>

<!--    Place front table-->

    <xacro:table_macro name="table_front" parent="table_base" width="0.7"
                       length="1.20" height="0.75"
                       tabletop_thickness="0.015" leg_radius="0.02">
        <origin xyz="${(0.9+0.7)/2} 0 0" rpy="0 0 0"/>
    </xacro:table_macro>

    <link name="table_beam">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://larcc_cell_description/meshes/minitec_45x45_1500.STL" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.045 0.045 1.5"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0" />
            <origin xyz="0.0 0.0 ${0.75/2-40-0.001}" rpy="0 0 0" />
            <inertia ixx="0.1" ixy="0"  ixz="0"
                     iyy="0.1" iyz="0"
                     izz="0.01" />
        </inertial>
    </link>

    <joint name="table_base_to_table_beam" type="fixed">
        <parent link="table_base" />
        <child link="table_beam" />
        <origin xyz="0.305 -0.625 0.0025" rpy="${M_PI/2} 0 0"/>
    </joint>

     <!-- Collision box representing the ceiling -->
    <link name="virtual_ceiling">
      <collision>
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <geometry>
          <box size="5 5 0.1"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <geometry>
          <box size="5 5 0.1"/>
        </geometry>
        <material name="red">
          <color rgba="0.5 0 0 0"/>
        </material>
      </visual>
    </link>
    <joint name="fixed_ceiling_joint" type="fixed">
      <parent link="world"/> <!-- Replace with your reference link -->
      <child link="virtual_ceiling"/>
      <origin xyz="0 0 1.8" rpy="0 0 0"/>
    </joint>

</robot>
