image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1004.6794 ,    0.     ,  653.83482,
            0.     , 1005.91774,  376.33007,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.157716, -0.248150, 0.004083, 0.003191, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1028.67355,    0.     ,  658.14844,    0.     ,
            0.     , 1033.48416,  378.65795,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]