image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [601.03061,   0.     , 331.12984,
           0.     , 601.79004, 240.14647,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.146985, -0.202498, 0.000237, 0.004770, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [616.93157,   0.     , 333.72475,   0.     ,
           0.     , 620.56452, 240.24804,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]