image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [603.05976,   0.     , 327.62599,
           0.     , 603.99231, 242.39845,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.139532, -0.171623, 0.004240, 0.002727, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [621.91207,   0.     , 329.16049,   0.     ,
           0.     , 622.62928, 244.16726,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]